version: "3.7"
    
networks:
  pmesp-cc-net:
    external: true

services:
  api:
    build: .
    container_name: gosign
    restart: unless-stopped
    ports:
        - 8082:8082
    # volumes:
    #   - ./:/go-sign
    entrypoint: sh -c 'go run -mod vendor *.go'
    networks:
      - pmesp-cc-net
