version: "3.7"

networks:
  development:

volumes:
  gosign-bashhistory:

services:
  dev:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    user: "1000"
    networks:
      - development
    volumes:
      - gosign-bashhistory:/commandhistory
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/go-sign
    working_dir: /go-sign
    command: go run main.go
    ports: 
      - 8080:8080
