package env

const (
	SERVER_PORT     = "PORT"
	FRONTEND_ORIGIN = "FRONTEND_ORIGIN"
	MONGO_USER      = "MONGO_USER"
	MONGO_PWD       = "MONGO_PWD"
	MONGO_URL       = "MONGO_URL"
	DATABASE_NAME   = "DATABASE_NAME"
)
